<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;



class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([[
            'login' => 'samir',
            'name' => 'samir RINAZ',
            'email' => 'samir@etna-alternance.net',
            'tags' => 'direction,technique',
            'logas'=> false,
            'groups'=> 'directeur',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'direction',
            'responsable' => 'aucun',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'deborah.cristiani',
            'name' => 'deborah CRISTIANI',
            'email' => 'deborah.cristiani@etna-learning.fr',
            'tags' => 'aucun',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service pedagogique & RH et Office Management',
            'responsable' => 'Samir RINAZ',
            'password' => Hash::make('password'),
            'super_admin' => TRUE
        ],
        [
            'login' => 'arnoul_l',
            'name' => 'Lutricia ARNOULD',
            'email' => 'arnoul_l@etna-alternance.net',
            'tags' => 'ip,suivi,manager',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service pedagogique',
            'responsable' => 'Deborah CRISTIANI',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'belgue_s',
            'name' => 'Sabri BELGUERMA',
            'email' => 'belgue_s@etna-alternance.net',
            'tags' => 'technique,alternant,assistant',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service pedagogique',
            'responsable' => 'Deborah CRISTIANI',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'carra_c',
            'name' => 'Cameron CARRA',
            'email' => 'carra_c@etna-alternance.net',
            'tags' => 'technique,ap',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service pedagogique',
            'responsable' => 'Deborah CRISTIANI',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'cros_b',
            'name' => 'Arthur CROS',
            'email' => 'cros_b@etna-alternance.net',
            'tags' => 'technique,master,c2w',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service pedagogique',
            'responsable' => 'Deborah CRISTIANI',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'daems_s',
            'name' => 'Sandra DAEMS',
            'email' => 'daems_s@etna-learning.fr',
            'tags' => 'ip,master',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service pedagogique',
            'responsable' => 'Deborah CRISTIANI',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'dehili_m',
            'name' => 'Mélissa DEHILI',
            'email' => 'dehili_m@etna-alternance.net',
            'tags' => 'suivi,ap',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service pedagogique',
            'responsable' => 'Deborah CRISTIANI',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'doumer_c',
            'name' => 'Clément DOUMERGUE',
            'email' => 'doumer_c@etna-alternance.net',
            'tags' => 'technique,master,c2w',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service pedagogique',
            'responsable' => 'Deborah CRISTIANI',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'lokwa_j',
            'name' => 'Jennifer LOKWA',
            'email' => 'lokwa_j@etna-learning.fr',
            'tags' => 'suivi,ap2bachelor',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service pedagogique',
            'responsable' => 'Deborah CRISTIANI',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'lequer_r',
            'name' => 'Robin LE QUEREC',
            'email' => 'lequer_r@etna-alternance.net',
            'tags' => 'technique,master',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service pedagogique',
            'responsable' => 'Deborah CRISTIANI',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'marais_j',
            'name' => 'Jérémie MARAIS',
            'email' => 'marais_j@etna-alternance.net',
            'tags' => 'technique,bachelor',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service pedagogique',
            'responsable' => 'Deborah CRISTIANI',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'moesan_j',
            'name' => 'Clément MOESAN',
            'email' => 'moesan_j@etna-alternance.net',
            'tags' => 'suivi,master',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service pedagogique',
            'responsable' => 'Deborah CRISTIANI',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'pankie_m',
            'name' => 'Mégane PANKIEWICZ',
            'email' => 'pankie_m@etna-alternance.net',
            'tags' => 'ip,ap,bachelor',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service pedagogique',
            'responsable' => 'Deborah CRISTIANI',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'torreg_l',
            'name' => 'Lisa TORREGROSSA',
            'email' => 'torreg_l@etna-alternance.net',
            'tags' => 'suivi,ap',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service pedagogique',
            'responsable' => 'Deborah CRISTIANI',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'tram_a',
            'name' => 'Anthony TRAM',
            'email' => 'tram_a@etna-alternance.net',
            'tags' => 'technique,c2w',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service pedagogique',
            'responsable' => 'Deborah CRISTIANI',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'seneze_v',
            'name' => 'Valerie SENEZERGUES',
            'email' => 'seneze_v@etna-alternance.net',
            'tags' => 'aucun',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service administratif',
            'responsable' => 'aucun',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'cheron_j',
            'name' => 'Jennifer CHERON',
            'email' => 'cheron_j@etna-learning.fr',
            'tags' => 'facturation',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service administratif',
            'responsable' => 'Valerie SENEZERGUES',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'daouah_f',
            'name' => 'Fanida DAOUAH',
            'email' => 'daouah_f@etna-learning.fr',
            'tags' => 'administration',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service administratif',
            'responsable' => 'Valerie SENEZERGUES',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'mohame_a',
            'name' => 'Sophie MOHAMED',
            'email' => 'mohame_a@etna-learning.fr',
            'tags' => 'administration,facturation',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service administratif',
            'responsable' => 'Valerie SENEZERGUES',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'moscou_c',
            'name' => 'Cédric MOSCOU',
            'email' => 'moscou_c@etna-learning.fr',
            'tags' => 'administration',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service administratif',
            'responsable' => 'Valerie SENEZERGUES',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'nkelez_e',
            'name' => 'Eliza NKELEZI',
            'email' => 'nkelez_e@etna-learning.fr',
            'tags' => 'facturation',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service administratif',
            'responsable' => 'Valerie SENEZERGUES',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'prodho_m',
            'name' => 'Magalie PRODHOMME',
            'email' => 'prodho_m@etna-learning.fr',
            'tags' => 'facturation,manager',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service administratif',
            'responsable' => 'Valerie SENEZERGUES',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'deland_c',
            'name' => 'Colyne DELANDE',
            'email' => 'deland_c@etna-alternance.net',
            'tags' => 'aucun',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service des relations école entreprises',
            'responsable' => 'Samir RINAZ',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'tony.pojer',
            'name' => 'Tony POJER',
            'email' => 'tony.pojer@etna-alternance.net',
            'tags' => 'aucun',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service des relations école entreprises',
            'responsable' => 'Samir RINAZ',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'silves_c',
            'name' => 'Cindy SILVESTRE',
            'email' => 'silves_c@etna-alternance.net',
            'tags' => 'aucun',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service des relations école entreprises',
            'responsable' => 'Samir RINAZ',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'delait_a',
            'name' => 'Lola DELAITRE',
            'email' => 'delait_a@etna-learning.fr',
            'tags' => 'aucun', 
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service des admissions',
            'responsable' => 'aucun',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'genevi_a',
            'name' => 'Aurélie GENEVIEVE',
            'email' => 'genevi_a@etna-learning.fr',
            'tags' => 'admission', 
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service des admissions',
            'responsable' => 'Lola DELAITRE',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'kemayo_k',
            'name' => 'Karen KEMAYOU',
            'email' => 'kemayo_k@etna-learning.fr',
            'tags' => 'com', 
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service des admissions',
            'responsable' => 'Lola DELAITRE',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'mungal_a',
            'name' => 'Aurélie MUNGALU MUKAMINA',
            'email' => 'mungal_a@etna-learning.fr',
            'tags' => 'admission', 
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'service des admissions',
            'responsable' => 'Lola DELAITRE',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'maudui_t',
            'name' => 'Thomas MAUDUIT',
            'email' => 'maudui_t@etna-alternance.net',
            'tags' => 'aucun', 
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'BLU',
            'responsable' => 'aucun',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'charpe_o',
            'name' => 'Oxana CHARPENTIER',
            'email' => 'charpe_o@etna-alternance.net',
            'tags' => 'asys', 
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'BLU',
            'responsable' => 'Thomas MAUDUIT',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'courta_f',
            'name' => 'Franck COURTAUX',
            'email' => 'courta_f@etna-alternance.net',
            'tags' => 'asys', 
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'BLU',
            'responsable' => 'Thomas MAUDUIT',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'demang_e',
            'name' => 'Ella DEMANGE',
            'email' => 'demang_e@etna-alternance.net',
            'tags' => 'dev', 
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'BLU',
            'responsable' => 'Thomas MAUDUIT',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'ladeir_j',
            'name' => 'Jérémy LADEIRA FERREIRA',
            'email' => 'ladeir_j@etna-alternance.net',
            'tags' => 'dev', 
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'BLU',
            'responsable' => 'Thomas MAUDUIT',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'memain_f',
            'name' => 'Flavien MEMAIN',
            'email' => 'memain_f@etna-alternance.net',
            'tags' => 'dev', 
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'BLU',
            'responsable' => 'Thomas MAUDUIT',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'tadros_j',
            'name' => 'Justine TADROS',
            'email' => 'tadros_j@etna-alternance.net',
            'tags' => 'dev', 
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'BLU',
            'responsable' => 'Thomas MAUDUIT',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'vandis_w',
            'name' => 'William VANDISTE', 
            'email' => 'vandis_w@etna-alternance.net',
            'tags' => 'asys,responsable', 
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'BLU',
            'responsable' => 'Thomas MAUDUIT',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'vignan_q',
            'name' => 'Quentin VIGNAN',
            'email' => 'vignan_q@etna-alternance.net',
            'tags' => 'devops', 
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'BLU',
            'responsable' => 'Thomas MAUDUIT',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'hanrot_j',
            'name' => 'Julie HANROT',
            'email' => 'hanrot_j@etna-alternance.net',
            'tags' => 'aucun', 
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'studio',
            'responsable' => 'aucun',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'driant_j',
            'name' => 'Jeanne DRIANT',
            'email' => 'driant_j@etna-alternance.net',
            'tags' => 'aucun', 
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'studio',
            'responsable' => 'Julie HANROT',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'guilma_a',
            'name' => 'Alexandre GUILMAIN',
            'email' => 'guilma_a@etna-learning.fr',
            'tags' => 'aucun', 
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'studio',
            'responsable' => 'Julie HANROT',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'daime_a',
            'name' => 'Adeline DAIME',
            'email' => 'adeline.daime@etna-alternance.net',
            'tags' => 'office',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'RH et Office Management',
            'responsable' => 'Deborah CRISTIANI',
            'password' => Hash::make('password'),
            'super_admin' => TRUE
        ],
        [
            'login' => 'aucun',
            'name' => 'Cissokho DAMBO',
            'email' => 'aucun',
            'tags' => 'propreté',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'RH et Office Management',
            'responsable' => 'Deborah CRISTIANI',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'aucun',
            'name' => 'Bintou DRAME',
            'email' => 'aucun',
            'tags' => 'propreté',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'RH et Office Management',
            'responsable' => 'Deborah CRISTIANI',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'aucun',
            'name' => 'Daniela FELIX MARTINS',
            'email' => 'aucun',
            'tags' => 'propreté',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'RH et Office Management',
            'responsable' => 'Deborah CRISTIANI',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'aucun',
            'name' => 'Goundoba GASSAMA',
            'email' => 'aucun',
            'tags' => 'propreté',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'RH et Office Management',
            'responsable' => 'Deborah CRISTIANI',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'thap_l',
            'name' => 'Linda THAP',
            'email' => 'thap_l@etna-alternance.net',
            'tags' => 'office',
            'logas'=> false,
            'groups'=> 'employée',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'RH et Office Management',
            'responsable' => 'Deborah CRISTIANI',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'akkari_j',
            'name' => 'Jawdan AKKARI',
            'email' => 'akkari_j@etna-alternance.net',
            'tags' => 'students',
            'logas'=> false,
            'groups'=> 'student',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'aucun',
            'responsable' => 'Cameron CARRA',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'elamar_a',
            'name' => 'Ali ELAMARI',
            'email' => 'elamar_a@etna-alternance.net',
            'tags' => 'students',
            'logas'=> false,
            'groups'=> 'students',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'aucun',
            'responsable' => 'Cameron CARRA',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'mchind_h',
            'name' => 'Hamadi MCHINDA',
            'email' => 'mchind_h@etna-alternance.net',
            'tags' => 'students',
            'logas'=> false,
            'groups'=> 'students',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'aucun',
            'responsable' => 'Cameron CARRA',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        [
            'login' => 'sbai_s',
            'name' => 'Soufiane SBAI',
            'email' => 'sbai_s@etna-alternance.net',
            'tags' => 'students',
            'logas'=> false,
            'groups'=> 'student',
            'firstconnexion'=>false,
            'login_date'=>'09:00:37',
            'service' => 'aucun',
            'responsable' => 'Cameron CARRA',
            'password' => Hash::make('password'),
            'super_admin' => FALSE
        ],
        
    ]);

    }
}

    